services:
  qgis-ch-grants:
    build: .
    container_name: qgis-ch-grants-${GRANTS_YEAR}
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT _SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./data/:/app/data/
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
